# 1. ConfigMap: it used to store non-sensitive configuration data
apiVersion: v1
kind: ConfigMap
metadata:
  name: pulseops-config
data:
  # These are safe to commit to Git
  APP_ENV: "staging"
  LOG_LEVEL: "info"
  WORKER_TIMEOUT: "300"

---
# 2. Secret: it used to store sensitive data (like database/redis URLs)
apiVersion: v1
kind: Secret
metadata:
  name: pulseops-secrets
type: Opaque
data:
  
  
 
  redis-url: cmVkaXM6Ly9yZWRpczo2Mzc5LzA= 
  
  
  database-url: cG9zdGdyZXM6Ly91c2VyOnBhc3N3b3JkQGxvY2FsaG9zdDo1NDMyL2pvYnNfZGI=